# Generated by Django 3.2.25 on 2024-10-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0002_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('cause_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('price_raised', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price_target', models.DecimalField(decimal_places=2, max_digits=9)),
                ('details', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.profile')),
            ],
        ),
    ]
