# Generated by Django 3.2.25 on 2024-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='cause_image',
            field=models.ImageField(null=True, upload_to='cause_images/'),
        ),
    ]
